export const homeData = [
  {
    id: 1,
    img: require("../../Public/divImg/dhaka.png"),
    title: "ঢাকা বিভাগ",
    titleEng: "dhaka",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 2,
    title: "রাজশাহী বিভাগ",
    titleEng: "rajshahi",
    img: require("../../Public/divImg/rajshahi.png"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 3,
    title: "খুলনা বিভাগ",
    titleEng: "khulna",
    img: require("../../Public/divImg/khulna.jpeg"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 4,
    title: "রংপুর বিভাগ",
    titleEng: "rangpur",
    img: require("../../Public/divImg/rangpur.png"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 5,
    title: "ময়মনসিংহ বিভাগ",
    titleEng: "mymensingh",
    img: require("../../Public/divImg/mymensingh.png"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 6,
    title: "সিলেট বিভাগ",
    titleEng: "sylhet",
    img: require("../../Public/divImg/sylhet.jpeg"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 7,
    title: "চট্টগ্রাম বিভাগ",
    titleEng: "chittagong",
    img: require("../../Public/divImg/chittagong.jpeg"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
  {
    id: 8,
    titleEng: "barisal",
    title: "বরিশাল বিভাগ",
    img: require("../../Public/divImg/barisal.jpeg"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat praesentium provident id. Ratione tempora repellendus dolorem itaque fugiat nostrum praesentium?",
  },
];
